baseurl = "https://dasc-1104-calebwilliamsblog.netlify.app/"
languageCode = "en-us"
title = "DASC 1104 Caleb Williams"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "About"
    url = "/about.md"
[[menu.main]]
    name = "Resume"
    url = "/resume-master/resume-example.pdf"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Calebwilliams67/statistical-methods"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/CalebWi69573556"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

